version: "3.8"

services:
  react-app:
    image: leeblock_react:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5123:5000"
    environment:
      NODE_ENV: production
      REACT_APP_BACKEND: ${REACT_APP_BACKEND} # Use environment variable substitution
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5123"]
      interval: 30s
      timeout: 10s
      retries: 3
